/* USER */

export const FETCH_USER = "FETCH_JOBS";
export const GET_USER = "GET_USER";
export const COMMIT_USER = "COMMIT_USER";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const COMMIT_PRODUCTS = "COMMIT_PRODUCTS";
export const FETCH_PRODUCT_GROUPS = "FETCH_PRODUCT_GROUPS";
export const COMMIT_ALL_PRODUCT_GROUPS = "COMMIT_ALL_PRODUCT_GROUPS";
export const FETCH_ALL_PRODUCT_GROUPS = "FETCH_ALL_PRODUCT_GROUPS";
export const COMMIT_PRODUCT_GROUPS = "COMMIT_PRODUCT_GROUPS";
export const CREATE_PRODUCT_GROUP = "CREATE_PRODUCT_GROUP";
export const ADD_PRODUCT_GROUP = "ADD_PRODUCT_GROUP";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_GROUPS = "GET_PRODUCT_GROUPS";
export const GET_ALL_PRODUCT_GROUPS = "GET_ALL_PRODUCT_GROUPS";
export const GET_TAB_PRODUCTS = "GET_TAB_PRODUCTS";
export const COMMIT_TAB_PRODUCTS = "COMMIT_TAB_PRODUCTS";

// POS
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const FIND_CART_INDEX = "FIND_CART_INDEX";
export const BEEP = "BEEP";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const ADD_CASH = "ADD_CASH";
export const UPDATE_CHANGE = "UPDATE_CHANGE";
export const GET_CHANGE = "GET_CHANGE";
export const GET_CASH = "GET_CASH";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";
export const UPDATE_CASH = "UPDATE_CASH";
export const CLEAR = "CLEAR";
export const SUBMIT = "SUBMIT";
export const UPDATE_KEYWORD = "UPDATE_KEYWORD";
export const GET_KEYWORD = "GET_KEYWORD";
export const SUBMITABLE = "SUBMITABLE";
export const COMMIT_TO_CART = "COMMIT_TO_CART";
export const COMMIT_FIND_INDEX = "COMMIT_FIND_INDEX";
export const GET_CART_INDEX = "GET_CART_INDEX";
export const ADD_KEYWORD = "ADD_KEYWORD";
export const GET_ITEMS_COUNT = "GET_ITEMS_COUNT";
export const SUBMIT_ORDER = "SUBMIT_ORDER";
export const GET_IS_SHOW_MODAL_RECEIPT = "GET_IS_SHOW_MODAL_RECEIPT";
export const CLOSE_MODAL_RECEIPT = "CLOSE_MODAL_RECEIPT";
export const GET_RECEIPT_NUMBER = "GET_RECEIPT_NUMBER";
export const GET_RECEIPT_DATE = "GET_RECEIPT_DATE";

// CUSTOMERS
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const COMMIT_CUSTOMERS = "COMMIT_CUSTOMERS";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
