# Generated by Django 4.1 on 2022-09-06 05:00

import core.modules
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='Transparent', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.modules.profile_image_file_path)),
                ('rank', models.SmallIntegerField(default=0)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('plu', models.IntegerField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productgroup')),
            ],
        ),
    ]
