# Generated by Django 4.1 on 2022-09-06 06:35

import core.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productgroup_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.modules.upload_image_file_path),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.modules.upload_image_file_path),
        ),
    ]
