# Generated by Django 4.1 on 2022-11-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_posorderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.posorder'),
        ),
    ]
