# Generated by Django 4.1 on 2022-11-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posorderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttax',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTaxes', to='core.product', unique=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
