# Generated by Django 4.1 on 2022-09-09 18:44

import core.modules
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image_alter_productgroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Transparent', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('null', None)], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_price_change_allowed',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('null', None)], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('null', None)], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tax_inclusive_price',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('null', None)], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_using_default_quantity',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('null', None)], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.modules.upload_image_file_path),
        ),
    ]
