# Generated by Django 4.1 on 2022-11-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producttax_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttax',
            unique_together=set(),
        ),
    ]
