# Generated by Django 4.1 on 2022-11-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producttax_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_purchase_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
    ]
