# Generated by Django 4.1 on 2022-09-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tax_warehouse_created_warehouse_updated_stock_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producttax',
            constraint=models.UniqueConstraint(fields=('product', 'tax'), name='unique_product_taxes'),
        ),
    ]
