# Generated by Django 4.1 on 2022-12-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_cost_alter_product_last_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('number', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='posorderitem',
            old_name='voide_by',
            new_name='voided_by',
        ),
        migrations.RenameField(
            model_name='productcomment',
            old_name='value',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='order_number',
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.posorder'),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='round_number',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='posprinterselection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PosPrinterSelections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='posorderitem',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
