# Generated by Django 4.1 on 2022-12-02 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cashregister_rename_voide_by_posorderitem_voided_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['document']},
        ),
        migrations.RemoveConstraint(
            model_name='posprinterselection',
            name='unique_printer_keys',
        ),
        migrations.RenameField(
            model_name='documentitem',
            old_name='price_before_tax_after_descount',
            new_name='price_before_tax_after_discount',
        ),
        migrations.AddField(
            model_name='document',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.cashregister'),
        ),
        migrations.AddField(
            model_name='posprinterselection',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PosPrinterSelections', to='core.cashregister'),
        ),
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.securitykey'),
        ),
        migrations.AddField(
            model_name='zreport',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z_reports', to='core.cashregister'),
        ),
        migrations.AlterField(
            model_name='posprinterselectionsettings',
            name='cut_paper',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='posprinterselectionsettings',
            name='open_cash_drawer',
            field=models.BooleanField(default=1),
        ),
        migrations.AddConstraint(
            model_name='posprinterselection',
            constraint=models.UniqueConstraint(fields=('key', 'cash_register'), name='unique_printer_keys'),
        ),
    ]
