# Generated by Django 4.1 on 2022-12-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingcash',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash', to='core.cashregister'),
        ),
    ]
