# Generated by Django 4.1 on 2022-12-11 22:40

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User = apps.get_model("core", "User")
    user1 = User.objects.get(id=1)
    Country = apps.get_model("core", "Country")
    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).bulk_create([
        Country(user=user1, name="Iraq", code="iq"),
        Country(user=user1, name="United Arab Emirates", code="uae"),
    ])


# def reverse_func(apps, schema_editor):
#     # forwards_func() creates two Country instances,
#     # so reverse_func() should delete them.
#     Country = apps.get_model("core", "Country")
#     db_alias = schema_editor.connection.alias
#     Country.objects.using(db_alias).filter(
#         user=1, name="USA", code="us").delete()
#     Country.objects.using(db_alias).filter(
#         user=1, name="France", code="fr").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paymenttype_ordinal'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
