# Generated by Django 4.1 on 2022-09-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_customerdiscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_enabled',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('null', None)], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
