# Generated by Django 4.1 on 2022-12-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_run_python_countries_addrecords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ('ordinal',)},
        ),
    ]
