# Generated by Django 4.1 on 2022-09-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_document_documentcategory_documentitem_documenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=250)),
                ('module', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_customer_required', models.BooleanField(default=False)),
                ('is_fiscal', models.BooleanField(default=True)),
                ('is_slip_required', models.BooleanField(default=False)),
                ('is_change_allowed', models.BooleanField(default=True)),
                ('ordinal', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_quick_payment', models.BooleanField(default=True)),
                ('open_cash_drawer', models.BooleanField(default=False)),
                ('shortcut', models.CharField(blank=True, max_length=30, null=True)),
                ('mark_as_paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('discount', models.SmallIntegerField(default=0)),
                ('discount_type', models.SmallIntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0)),
                ('discount_type', models.FloatField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('voide_by', models.SmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('bundle', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosPrinterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('printer_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ('rank',)},
        ),
        migrations.CreateModel(
            name='PosPrinterSelectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_width', models.SmallIntegerField(default=32)),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
                ('feed_lines', models.SmallIntegerField(default=0)),
                ('cut_paper', models.SmallIntegerField(default=1)),
                ('print_bitmap', models.SmallIntegerField(default=0)),
                ('open_cash_drawer', models.SmallIntegerField(default=1)),
                ('cash_drawer_command', models.CharField(max_length=100)),
                ('header_alignment', models.SmallIntegerField(default=0)),
                ('footer_alignment', models.SmallIntegerField(default=0)),
                ('is_formatting_enabled', models.BooleanField(default=False)),
                ('printer_type', models.SmallIntegerField(default=0)),
                ('number_of_copies', models.SmallIntegerField(default=1)),
                ('code_page', models.SmallIntegerField(default=-1)),
                ('character_set', models.SmallIntegerField(default=-1)),
                ('margin', models.SmallIntegerField(default=0)),
                ('left_margin', models.FloatField(default=1)),
                ('top_margin', models.FloatField(default=0)),
                ('right_margin', models.FloatField(default=0)),
                ('bottom_margin', models.FloatField(default=0)),
                ('print_barcode', models.SmallIntegerField(default=1)),
                ('font_name', models.CharField(max_length=100)),
                ('font_size_percent', models.FloatField(default=100.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pos_printer_selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.posprinterselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PosPrinterSelectionSettings',
            },
        ),
        migrations.AddConstraint(
            model_name='posprinterselection',
            constraint=models.UniqueConstraint(fields=('id', 'key'), name='unique_printer_keys'),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.posorder'),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='core.product'),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.document'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='core.paymenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
