# Generated by Django 4.1 on 2022-09-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_migration_payment_paymenttype_posorder_posorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('days_of_week', models.SmallIntegerField()),
                ('is_enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tax',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_clocked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='is_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posprinterselectionsettings',
            name='pos_printer_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_selection_settings', to='core.posprinterselection'),
        ),
        migrations.AlterField(
            model_name='posprinterselectionsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_selection_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_price_change_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_tax_inclusive_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_using_default_quantity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productgroup'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tax',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tax',
            name='is_tax_on_total',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorder_poing', models.FloatField(default=0)),
                ('preferred_quantity', models.SmallIntegerField(default=1)),
                ('is_low_stock_warning_enabled', models.BooleanField(default=True)),
                ('low_stock_warning_quantity', models.SmallIntegerField(default=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_controls', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_controls', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_controls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartingCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_cash_type', models.SmallIntegerField(default=0)),
                ('z_report_number', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_cashes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityKey',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=uuid.uuid4)),
                ('discount_type', models.SmallIntegerField(default=0)),
                ('price_type', models.SmallIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('is_conditional', models.BooleanField(default=False)),
                ('quantity', models.FloatField(default=1)),
                ('condition_type', models.SmallIntegerField(default=0)),
                ('quantity_limit', models.SmallIntegerField(default=0)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='core.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPrintStations', to='core.printstation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPrintStations', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPrintStations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroupPrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productGroupPrintStations', to='core.printstation')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productGroupPrintStations', to='core.productgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productGroupPrintStations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintStationPosPrinterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_printer_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posprinterselection')),
                ('print_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.printstation')),
            ],
        ),
        migrations.CreateModel(
            name='PosPrinterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=100, unique=True)),
                ('paper_width', models.SmallIntegerField(default=32)),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
                ('feed_lines', models.SmallIntegerField(default=0)),
                ('cut_paper', models.SmallIntegerField(default=1)),
                ('print_bitmap', models.SmallIntegerField(default=0)),
                ('open_cash_drawer', models.SmallIntegerField(default=1)),
                ('cash_drawer_command', models.CharField(max_length=100)),
                ('header_alignment', models.SmallIntegerField(default=0)),
                ('footer_alignment', models.SmallIntegerField(default=0)),
                ('is_formatting_enabled', models.BooleanField(default=False)),
                ('printer_type', models.SmallIntegerField(default=0)),
                ('number_of_copies', models.SmallIntegerField(default=1)),
                ('code_page', models.SmallIntegerField(default=-1)),
                ('character_set', models.SmallIntegerField(default=-1)),
                ('margin', models.SmallIntegerField(default=0)),
                ('left_margin', models.FloatField(default=1)),
                ('top_margin', models.FloatField(default=0)),
                ('right_margin', models.FloatField(default=0)),
                ('bottom_margin', models.FloatField(default=0)),
                ('print_barcode', models.SmallIntegerField(default=1)),
                ('font_name', models.CharField(max_length=100)),
                ('font_size_percent', models.FloatField(default=100.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PosPrinterSettings',
            },
        ),
        migrations.AddIndex(
            model_name='stockcontrol',
            index=models.Index(fields=['product'], name='stock_control_product_index'),
        ),
        migrations.AddConstraint(
            model_name='startingcash',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_id'),
        ),
        migrations.AddConstraint(
            model_name='productprintstation',
            constraint=models.UniqueConstraint(fields=('product', 'print_station'), name='product_print_station'),
        ),
        migrations.AddConstraint(
            model_name='productgroupprintstation',
            constraint=models.UniqueConstraint(fields=('product_group', 'print_station'), name='pg_print_station'),
        ),
        migrations.AddConstraint(
            model_name='printstationposprinterselection',
            constraint=models.UniqueConstraint(fields=('print_station', 'pos_printer_selection'), name='unique_printer_pos_printer_selection'),
        ),
        migrations.AddConstraint(
            model_name='posprintersettings',
            constraint=models.UniqueConstraint(fields=('id', 'printer_name'), name='unique_printer_name'),
        ),
    ]
