# Generated by Django 4.1 on 2022-09-12 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_migration_payment_paymenttype_posorder_posorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroupPrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='posprinterselectionsettings',
            name='pos_printer_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_selection_settings', to='core.posprinterselection'),
        ),
        migrations.AlterField(
            model_name='posprinterselectionsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_selection_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_controls', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_controls', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_controls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartingCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_cash_type', models.SmallIntegerField(default=0)),
                ('z_report_number', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_cashes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityKey',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintStationPosPrinterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_printer_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posprinterselection')),
                ('print_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.printstation')),
            ],
        ),
        migrations.CreateModel(
            name='PosPrinterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=100, unique=True)),
                ('paper_width', models.SmallIntegerField(default=32)),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
                ('feed_lines', models.SmallIntegerField(default=0)),
                ('cut_paper', models.SmallIntegerField(default=1)),
                ('print_bitmap', models.SmallIntegerField(default=0)),
                ('open_cash_drawer', models.SmallIntegerField(default=1)),
                ('cash_drawer_command', models.CharField(max_length=100)),
                ('header_alignment', models.SmallIntegerField(default=0)),
                ('footer_alignment', models.SmallIntegerField(default=0)),
                ('is_formatting_enabled', models.BooleanField(default=False)),
                ('printer_type', models.SmallIntegerField(default=0)),
                ('number_of_copies', models.SmallIntegerField(default=1)),
                ('code_page', models.SmallIntegerField(default=-1)),
                ('character_set', models.SmallIntegerField(default=-1)),
                ('margin', models.SmallIntegerField(default=0)),
                ('left_margin', models.FloatField(default=1)),
                ('top_margin', models.FloatField(default=0)),
                ('right_margin', models.FloatField(default=0)),
                ('bottom_margin', models.FloatField(default=0)),
                ('print_barcode', models.SmallIntegerField(default=1)),
                ('font_name', models.CharField(max_length=100)),
                ('font_size_percent', models.FloatField(default=100.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_printer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PosPrinterSettings',
            },
        ),
        migrations.AddConstraint(
            model_name='stockcontrol',
            constraint=models.UniqueConstraint(fields=('product',), name='stock_control_product'),
        ),
        migrations.AddConstraint(
            model_name='startingcash',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_id'),
        ),
        migrations.AddConstraint(
            model_name='printstationposprinterselection',
            constraint=models.UniqueConstraint(fields=('print_station', 'pos_printer_selection'), name='unique_printer_pos_printer_selection'),
        ),
        migrations.AddConstraint(
            model_name='posprintersettings',
            constraint=models.UniqueConstraint(fields=('id', 'printer_name'), name='unique_printer_name'),
        ),
    ]
