# Generated by Django 4.1 on 2022-09-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_printstation_productgroupprintstation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockcontrol',
            name='stock_control_product',
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='is_low_stock_warning_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='low_stock_warning_quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='preferred_quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='recorder_poing',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='stockcontrol',
            index=models.Index(fields=['product'], name='stock_control_product_index'),
        ),
    ]
