# Generated by Django 4.1 on 2022-09-12 11:35

import core.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_printstation_promotion_tax_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=core.modules.upload_image_file_path),
        ),
    ]
