# Generated by Django 4.1 on 2022-09-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_stockcontrol_stock_control_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_clocked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
