# Generated by Django 4.1 on 2022-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_recorder_poing_stockcontrol_reorder_poing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startingcash',
            options={'verbose_name_plural': 'starting cash'},
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
