# Generated by Django 4.1 on 2022-11-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_product_group_product_parent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product',
            field=models.BooleanField(default=True),
        ),
    ]
