# Generated by Django 4.1 on 2022-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_productgroup_is_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
