DROP TABLE IF EXISTS Promotion;
DROP TABLE IF EXISTS PromotionItem;

CREATE TABLE Promotion 
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	Name TEXT NOT NULL, 
	StartDate DATETIME,
	EndDate DATETIME,
	IsEnabled INTEGER(1) NOT NULL DEFAULT (1)
);

CREATE TABLE PromotionItem
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	PromotionId INTEGER REFERENCES Promotion (Id) ON DELETE CASCADE NOT NULL,
	Quantity NUMERIC NOT NULL DEFAULT(0),
	Value NUMERIC NOT NULL DEFAULT (0)
);