ALTER TABLE Product ADD COLUMN Cost NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE Product ADD COLUMN Margin NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE DocumentItem ADD COLUMN ProductCost NUMERIC NOT NULL DEFAULT 0;