DROP TABLE IF EXISTS Promotion;
DROP TABLE IF EXISTS PromotionItem;

CREATE TABLE Promotion 
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	Name TEXT NOT NULL, 
	StartDate DATETIME,
	StartTime DATETIME,
	EndDate DATETIME,
	EndTime DATETIME,
	DaysOfWeek INTEGER NOT NULL,
	IsEnabled INTEGER(1) NOT NULL DEFAULT (1)
);

CREATE TABLE PromotionItem
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	PromotionId INTEGER REFERENCES Promotion (Id) ON DELETE CASCADE NOT NULL,
	Uid INTEGER NOT NULL,
	DiscountType INTEGER NOT NULL DEFAULT(0),
	PriceType INTEGER NOT NULL DEFAULT(0),
	Value NUMERIC NOT NULL DEFAULT(0),
	IsConditional INTEGER(1) NOT NULL DEFAULT (1),
	Quantity NUMERIC NOT NULL DEFAULT(0),
	ConditionType INTEGER NOT NULL DEFAULT(0),
	QuantityLimit NUMERIC NOT NULL DEFAULT(0)
);

ALTER TABLE OrderItem ADD COLUMN IsFeatured INT(1) NOT NULL DEFAULT 0;