DROP TABLE IF EXISTS CustomerDiscount;

CREATE TABLE CustomerDiscount 
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	CustomerId INTEGER REFERENCES Customer (Id) ON DELETE CASCADE NOT NULL, 
	Type INTEGER (1) NOT NULL DEFAULT (0), 
	Uid INTEGER, 
	Value REAL NOT NULL DEFAULT (0), 
	CONSTRAINT UK_CustomerDiscount UNIQUE (CustomerId, Type, Uid)
);