ALTER TABLE Customer ADD COLUMN IsEnabled INTEGER (1) NOT NULL DEFAULT 1;
ALTER TABLE Customer ADD COLUMN IsCustomer INTEGER (1) NOT NULL DEFAULT 1;
ALTER TABLE Customer ADD COLUMN IsSupplier INTEGER (1) NOT NULL DEFAULT 1;