DROP TABLE IF EXISTS PosPrinterSettings;
DROP TABLE IF EXISTS PosPrinterSelection;

CREATE TABLE PosPrinterSettings 
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	PrinterName TEXT NOT NULL CONSTRAINT UK_PrinterName UNIQUE, 
	PaperWidth INTEGER (5) NOT NULL DEFAULT (32), 
	Header TEXT, 
	Footer TEXT,
	FeedLines INTEGER (3) NOT NULL DEFAULT (0), 
	CutPaper INTEGER(1) NOT NULL DEFAULT (1),
	PrintBitmap INTEGER(1) NOT NULL DEFAULT (0)
);

CREATE TABLE PosPrinterSelection
(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	Key TEXT NOT NULL CONSTRAINT UK_PrinterKey UNIQUE, 
	PrinterName TEXT, 
	IsEnabled INTEGER (1) NOT NULL DEFAULT (0)
);