ALTER TABLE PaymentType ADD COLUMN MarkAsPaid INT(1) NOT NULL DEFAULT 1;
ALTER TABLE Document ADD COLUMN PaidStatus INTEGER NOT NULL DEFAULT 0;

UPDATE Document SET PaidStatus=2 WHERE DocumentTypeId IN (1,2,4);