export const products = [
  {
    id: 1,
    product: {
      id: 1,
      name: "Eggplant",
      code: "622179",
      description:
        "Build fun stuff in the cloud. It's a lot of fun, we promise!",
      age_restriction: null,
      price: 500.0,
      is_tax_inclusive_price: false,
      is_price_change_allowed: false,
      is_service: false,
      is_using_default_quantity: false,
      cost: 450.0,
      margin: "0.000",
      image:
        "http://127.0.0.1:8000/media/uploads/product/3e19d676-cc04-44b4-8c5b-4de1bcd2f118.jpg",
      color: "Transparent",
      is_enabled: true,
      measurement_unit: "Kg",
      plu: 2,
      last_purchase_price: 0.0,
      rank: 0,
      user: 1,
      product_group: 2,
      currency: 1,
      stock_quantity: 500,
    },
    quantity: 1,
    discount: 10,
  },
  {
    id: 2,
    product: {
      id: 2,
      name: "Cucumber",
      code: "635788gy9l",
      description:
        "Author act increase worry yeah. Positive medical shake include serious check state.",
      age_restriction: null,
      price: 1250.0,
      is_tax_inclusive_price: false,
      is_price_change_allowed: false,
      is_service: false,
      is_using_default_quantity: true,
      cost: 0.0,
      margin: "0.000",
      image:
        "http://127.0.0.1:8000/media/uploads/product/b7d96ae0-fede-46f9-ac1c-0d7f931a657c.jpg",
      color: "Transparent",
      is_enabled: true,
      measurement_unit: "Kg",
      plu: 1,
      last_purchase_price: 0.0,
      rank: 0,
      user: 1,
      product_group: 2,
      currency: 1,
      stock_quantity: 250,
    },
    quantity: 1,
    discount: 10,
  },
  {
    id: 3,
    product: {
      id: 3,
      name: "Banana",
      code: "62217923231",
      description:
        "Author act increase worry yeah. Positive medical shake include serious check state.",
      age_restriction: null,
      price: 2000.0,
      is_tax_inclusive_price: false,
      is_price_change_allowed: false,
      is_service: false,
      is_using_default_quantity: true,
      cost: 0.0,
      margin: "0.000",
      image:
        "http://127.0.0.1:8000/media/uploads/product/7bdcd8a6-f161-4f03-ad59-4db2f5dd0282.jpg",
      color: "Transparent",
      is_enabled: true,
      measurement_unit: "Kg",
      plu: 1,
      last_purchase_price: 0.0,
      rank: 0,
      user: 1,
      product_group: 3,
      currency: 1,
      stock_quantity: 123,
    },
    quantity: 1,
    discount: 10,
  },
  {
    id: 4,
    product: {
      id: 4,
      name: "Watermelon",
      code: "62217955433300",
      description: "Be a leader for everyone. Leadership builds character.",
      age_restriction: null,
      price: 1750.0,
      is_tax_inclusive_price: false,
      is_price_change_allowed: false,
      is_service: false,
      is_using_default_quantity: true,
      cost: 0.0,
      margin: "0.000",
      image:
        "http://127.0.0.1:8000/media/uploads/product/c77a249c-d91a-442e-b5d5-79e0bdfb2581.jpg",
      color: "Transparent",
      is_enabled: true,
      measurement_unit: "Kg",
      plu: 1,
      last_purchase_price: 0.0,
      rank: 0,
      user: 1,
      product_group: 3,
      currency: 1,
      stock_quantity: 75,
    },
    quantity: 1,
    discount: 10,
  },
];
